name: Deploy Frost API to GitHub Packages

on:
  push:
    branches: [main]
    paths: [ 'api/**', 'gradle/libs.versions.toml' ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: '21'
  NODE_VERSION: '22'

jobs:
  sonatype:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - id: vars
        run: echo "short_commit_hash=${GITHUB_SHA::10}" >> $GITHUB_OUTPUT
      - name: Publish to Central via Build
        if: github.repository_owner == 'WJMAG'
        run: |
          ./gradlew publish --no-configuration-cache
          echo "Version: ${VERSION}" >> $GITHUB_STEP_SUMMARY
        env:
          VERSION: ${{ steps.vars.outputs.short_commit_hash }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
