name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths: [ 'src/**' ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Set up JDK for Gradle
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Fix gradle permissions
        run: chmod +x ./gradlew

      # Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug

      # Log in to the GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6.16.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
          tags: |
            ghcr.io/minestudio-host/ug:server
