name: Publish Module to Another Repo

on:
  push:
    branches: [ main ]
    paths: [ 'test-shard/**' ]
  workflow_dispatch:

jobs:
  publish-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git for target repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push module to target repo
        env:
          TARGET_REPO: MineStudio-Host/example-shard.git  # Just the path, not full URL
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Or use a PAT if cross-org
        run: |
          # Create a temporary directory
          mkdir -p tmp_publish
          
          # Copy only the module you want to publish
          cp -r test-shard/ tmp_publish/
          
          # Clone the target repo using authenticated URL
          git clone https://$GH_TOKEN@github.com/$TARGET_REPO target_repo
          cd target_repo
          
          # Copy the module content
          cp -r ../tmp_publish/* .
          
          # Commit and push
          git add .
          git commit -m "chore(auto): Update test-shard from Frost repo"
          git push https://$GH_TOKEN@github.com/$TARGET_REPO
