name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  remove-old-artifacts:
    runs-on: arc-runner-set
    timeout-minutes: 10

    # For private repos
    permissions:
      actions: write

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '12 hours'
          skip-recent: 2